project:
  type: website
  output-dir: _site

website:
  title: "Sudan Blueprint"
  site-url: https://sudan-blueprint.github.io/sudan-blueprint-site/
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Contribute"
        href: contribute.qmd
      - text: "Case Studies"
        menu:
          - text: "Maash Alnass Observatory (EN)"
            href: case-studies/maash-observatory-en.qmd
          - text: "مرصد معاش الناس (AR)"
            href: case-studies/maash-observatory-ar.qmd
      - text: "Toolkits"
        href: toolkits/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    code-copy: true
    sidebar:
      contents:
        - text: "Maash Alnass Observatory (EN)"
          href: case-studies/maash-observatory-en.qmd
        - text: "مرصد معاش الناس (AR)"
          href: case-studies/maash-observatory-ar.qmd
